### ISSUE TITLE
Run Problems

### ISSUE THREAD

**Issue by Ryn-07** [nErrorDreamer/GoogleDorker#1]
Hello friend, I want to ask ... When I run the Tools, I am always rushed to open with ... Is this really like that? Or am I using it wrong?

**Comment by nerrorsec** [comment]
I think you are talking about some links opening when the tool is run. Yeah the tool was like that before. Recently some hours ago the update has been pushed. So just download the tool try it now.

**Comment by nerrorsec** [comment]
Feel free to ping me if you face any issue. Thank You

**Comment by Ryn-07** [comment]
![Gambar 1](https://user-images.githubusercontent.com/49482036/55960484-16921400-5c97-11e9-8487-8bb8e26430f2.png)

Like that ! Is my way usage wrong ? Maybe I need step by step how to use the script. Thankyou

**Comment by Ryn-07** [comment]
And also This problem 
![Gambar 2](https://user-images.githubusercontent.com/49482036/55961874-f748b600-5c99-11e9-95a9-0b3771a83bc8.png)

**Comment by nerrorsec** [comment]
https://www.pythoncentral.io/execute-python-script-file-shell/ should help with executing the python script. I think you already figured out how to do it.

For the error thrown, you are missing a module. Installing the module will fix it.
   pip3 install BeautifulSoup
https://youtu.be/zPMr0lEMqpo should help.

Also I have updated the usage and added a file called requirements.txt

**Comment by Ryn-07** [comment]
Thx I will try again

Pada tanggal Jum, 12 Apr 2019 08.49, nError <notifications@github.com>
menulis:

**Comment by nerrorsec** [comment]
Sure. I am closing this issue now.
