### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by Mikewins1** [nErrorDreamer/GoogleDorker#2]
root@kali:~/Desktop/GoogleDorker# pip3 install -r requirements.txt
Collecting beautifulsoup (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2r4cqruk/beautifulsoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2r4cqruk/beautifulsoup/
root@kali:~/Desktop/GoogleDorker# 

**Describe the bug**

**To Reproduce**
2. Do '....'

**Expected behavior**

**Additional context**

**Comment by nerrorsec** [comment]
Can you try "pip install -r requirements" ?

**Comment by Mikewins1** [comment]
root@kali:~/Desktop/GoogleDorker# pip install -r requirements.txt 
Requirement already satisfied: beautifulsoup in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (3.2.1)
Collecting aubprocess (from -r requirements.txt (line 2))
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/aubprocess/

root@kali:~/Desktop/GoogleDorker#

**Comment by nerrorsec** [comment]
I have updated the file. Can you check again?

**Comment by Mikewins1** [comment]
root@kali:~/Desktop/GoogleDorker# pip3 install -r requirements.txt
Collecting beautifulsoup (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mzwxkppg/beautifulsoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-mzwxkppg/beautifulsoup/
root@kali:~/Desktop/GoogleDorker# pip install -r requirements.txt 
Requirement already satisfied: beautifulsoup in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (3.2.1)
Collecting aubprocess (from -r requirements.txt (line 2))
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/aubprocess/

root@kali:~/Desktop/GoogleDorker#

**Comment by nerrorsec** [comment]
The problem seems to be on your end rather than with the script.
The last thing I can say is download and unzip the file from here and move them to python3/dist-packages/
[bs4.zip](https://github.com/nErrorDreamer/GoogleDorker/files/3156082/bs4.zip)

**Comment by nerrorsec** [comment]
beautifulsoup has been removed in the latest update. Please check if you have any problems.

**Comment by nerrorsec** [comment]
Seems fine. Thanks.
